{"name": "test_orchestrator_hitl_timeout", "status": "broken", "statusDetails": {"message": "AttributeError: <function send_slack_message at 0x118b8cfe0> does not have the attribute 'send_slack_message'", "trace": "def test_orchestrator_hitl_timeout():\n>       result = run_orchestrator_command(\"start-workflow\", \"automated_deployment\")\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\ntests/integration/workflows/orchestrator_timeout_fallback_test.py:4: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/integration/workflows/test_helpers.py:22: in run_orchestrator_command\n    with mock_slack_notifications():\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/mock.py:1497: in __enter__\n    original, local = self.get_original()\n                      ^^^^^^^^^^^^^^^^^^^\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <unittest.mock._patch object at 0x11ba70310>\n\n    def get_original(self):\n        target = self.getter()\n        name = self.attribute\n    \n        original = DEFAULT\n        local = False\n    \n        try:\n            original = target.__dict__[name]\n        except (AttributeError, KeyError):\n            original = getattr(target, name, DEFAULT)\n        else:\n            local = True\n    \n        if name in _builtins and isinstance(target, ModuleType):\n            self.create = True\n    \n        if not self.create and original is DEFAULT:\n>           raise AttributeError(\n                \"%s does not have the attribute %r\" % (target, name)\n            )\nE           AttributeError: <function send_slack_message at 0x118b8cfe0> does not have the attribute 'send_slack_message'\n\n/opt/homebrew/Cellar/python@3.13/3.13.5/Frameworks/Python.framework/Versions/3.13/lib/python3.13/unittest/mock.py:1467: AttributeError"}, "start": 1753819420671, "stop": 1753819420672, "uuid": "211f6d8b-c5c9-4aa1-872d-4396e42e6bc4", "historyId": "4a7ea8dac13ab16fc89d3e9228a9b7b9", "testCaseId": "4a7ea8dac13ab16fc89d3e9228a9b7b9", "fullName": "tests.integration.workflows.orchestrator_timeout_fallback_test#test_orchestrator_hitl_timeout", "labels": [{"name": "parentSuite", "value": "tests.integration.workflows"}, {"name": "suite", "value": "orchestrator_timeout_fallback_test"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.integration.workflows.orchestrator_timeout_fallback_test"}], "titlePath": ["tests", "integration", "workflows", "orchestrator_timeout_fallback_test.py"]}