{"name": "test_os_path_errors", "status": "passed", "description": "Test handling of os.path errors.", "start": 1753819436376, "stop": 1753819436377, "uuid": "7d6688e0-4e85-40c2-a7b2-437e77c2e814", "historyId": "98cb21395cb9710b7915efd62792f314", "testCaseId": "98cb21395cb9710b7915efd62792f314", "fullName": "tests.unit.core.test_validate_agent_resources_coverage.TestErrorHandling#test_os_path_errors", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_validate_agent_resources_coverage"}, {"name": "subSuite", "value": "TestErrorHandling"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_validate_agent_resources_coverage"}], "titlePath": ["tests", "unit", "core", "test_validate_agent_resources_coverage.py", "TestErrorHandling"]}