{"name": "test_file_open_error", "status": "passed", "description": "Test handling of file open errors.", "start": 1753819436373, "stop": 1753819436374, "uuid": "b08f90e7-049e-4ed3-b8cd-9bd6aefec22c", "historyId": "2e7a9ca4daeb113aa858a0f6cafc2458", "testCaseId": "2e7a9ca4daeb113aa858a0f6cafc2458", "fullName": "tests.unit.core.test_validate_agent_resources_coverage.TestErrorHandling#test_file_open_error", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_validate_agent_resources_coverage"}, {"name": "subSuite", "value": "TestErrorHandling"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_validate_agent_resources_coverage"}], "titlePath": ["tests", "unit", "core", "test_validate_agent_resources_coverage.py", "TestErrorHandling"]}