{"name": "test_publish_with_subscriber_error", "status": "passed", "description": "Test publishing when subscriber callback raises an error.", "attachments": [{"name": "log", "source": "fa89c557-0949-4938-9834-626bd58a6895-attachment.txt", "type": "text/plain"}], "start": 1753819429107, "stop": 1753819429108, "uuid": "30fdda66-a056-40f5-af2b-981199db22a0", "historyId": "e1799ff980cd1be8a4ab80131b7ab65b", "testCaseId": "e1799ff980cd1be8a4ab80131b7ab65b", "fullName": "tests.unit.core.test_message_bus_coverage.TestMessageBusPublish#test_publish_with_subscriber_error", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_message_bus_coverage"}, {"name": "subSuite", "value": "TestMessageBusPublish"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_message_bus_coverage"}], "titlePath": ["tests", "unit", "core", "test_message_bus_coverage.py", "TestMessageBusPublish"]}