{"name": "test_os_path_getsize_errors", "status": "passed", "description": "Test handling of os.path.getsize errors.", "start": 1753819436380, "stop": 1753819436381, "uuid": "33b5e520-4e7d-4d96-9e2c-509f4d959e50", "historyId": "2ecbcd630c4908073dda60861538c550", "testCaseId": "2ecbcd630c4908073dda60861538c550", "fullName": "tests.unit.core.test_validate_agent_resources_coverage.TestErrorHandling#test_os_path_getsize_errors", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_validate_agent_resources_coverage"}, {"name": "subSuite", "value": "TestErrorHandling"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_validate_agent_resources_coverage"}], "titlePath": ["tests", "unit", "core", "test_validate_agent_resources_coverage.py", "TestErrorHandling"]}